POST http://localhost:5000/cities
content-type: application/json 

{
    "name": "sacramento",
    "description": "the capital of california",
    "image": "https://images.contentstack.io/v3/assets/blt00454ccee8f8fe6b/blt32fb0ace9994de49/605c0a9fcc77b20f047aa55d/US_Sacramento_US_Header.jpg"
}